id: AC41A594A
title: A Prayer for the Swift Return of the Fourth Kyabje Dodrupchen Rinpoche
type: translation
pechas:
- IE62CF34B
- IF737F7F1
- IAAFF285F
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:55:08.766251
  last_modified_at: 2023-01-04 11:55:08.766255
  collections:
  - Fourth Dodrupchen Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IE62CF34B/8202: C180
  IF737F7F1/847A: C180
  IAAFF285F/91D3: C180
